---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-reksy
  namespace: staging
  labels:
    account: web-reksy

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"http":"HTTP2"}'
  name: web-reksy
  labels:
    app: web-reksy
    service: web-reksy
  namespace: staging
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: web-reksy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-reksy
  labels:
    app: web-reksy
    version: v1
  namespace: staging
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: web-reksy
      version: v1
  template:
    metadata:
      labels:
        app: web-reksy
        version: v1
    spec:
      containers:
        - image: reksy737/simpelgoweb:latest
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
