name: CI

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: reksy-v1    # Add your cluster name here.
  GKE_ZONE: asia-southeast1-a   # Add your cluster zone here.
  DEPLOYMENT_NAME: web-reksy # Add your deployment name here.

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to docker hub
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: reksy737/simpelgoweb:build${{github.run_number}}
          
      - name: setup gcloud cli
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      
      - name: Get the GKE credential
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      
      - name: deploy new image
        run: |-
          kubectl set image deployment/web-reksy app=reksy737/simpelgoweb:build${{github.run_number}} -n staging
